CREATE DATABASE JOB_PORTAL_DATABASE;
USE JOB_PORTAL_DATABASE;

CREATE TABLE USER_REGISTRATION (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 USERNAME  VARCHAR(50) UNIQUE NOT NULL, 
  EMAILID VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  MOBILENUMBER BIGINT NOT NULL, 
  WORKSTATUS VARCHAR(50) NOT NULL, 
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE EMPLOYER_REGISTRATION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) UNIQUE NOT NULL, 
  EMAILID VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  MOBILENUMBER BIGINT NOT NULL, 
  COMPANYNAME VARCHAR(50) NOT NULL, 
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Job_Posting_Details (
    id INT PRIMARY KEY AUTO_INCREMENT,
    company_name VARCHAR(100),
    job_title VARCHAR(100),
    location VARCHAR(100),
    salary_range VARCHAR(50),
    skills_required TEXT,
    educational_qualification VARCHAR(100),
    number_of_openings INT,
    application_deadline DATE,
    contact_info VARCHAR(100),
    company_website VARCHAR(255),
    job_type VARCHAR(50),
    experience_required VARCHAR(50),
    job_description TEXT
);

CREATE TABLE USER_RESUME_DETAILS(
ID INT auto_increment primary key, 
USER_NAME varchar(50) NOT null,
FILE_NAME varchar(255),
FILE_TYPE varchar(100),
FILE_DATA longblob,
UPLOADED_AT datetime default current_timestamp 
);





